### ISSUE TITLE
Create Comment Entity (TypeORM)

### ISSUE THREAD

**Issue by ahzia** [StartSteps-Digital-Education-GmbH/News-App#21]
Develop the `Comment` entity using TypeORM to represent user comments in the database. This entity will store information about comments on news items, linking them to users and news entries.  

**Requirements:**  
- Define a new `Comment` entity with the following fields:  
  - `id`: Primary key, auto-generated.  
  - `content`: Text content of the comment (non-nullable).  
  - `userId`: Foreign key referencing the `User` entity (non-nullable).  
  - `newsId`: Foreign key referencing the `News` entity (non-nullable).  
  - `timestamp`: Timestamp of when the comment was created (default to the current time).  
- Establish relationships:  
  - Many-to-One relationship with the `User` entity.  
  - Many-to-One relationship with the `News` entity.  
- Add validations:  
  - Ensure `content` is non-empty and within the acceptable character limit.  
- Ensure the table is created in the database upon running migrations.  

**Acceptance Criteria:**  
- The `Comment` entity is added to the project and follows TypeORM conventions.  
- Relationships with `User` and `News` entities are properly configured and functional. 
- The entity is tested for valid and invalid scenarios (e.g., missing fields, invalid relationships).

**Comment by bojana-petroska** [comment]
I had to make the entity so I can save the comment to the repository

**Comment by ahzia** [comment]
@bojana-petroska both of the issues can be connected to the same PR.
